name: Deploy to Firebase Hosting

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: "20"
    - name: Enable Corepack
      run: corepack enable && corepack prepare pnpm@latest --activate
    - name: Install dependencies
      working-directory: apps/not-splitwise
      run: pnpm install --frozen-lockfile || pnpm install
    - name: Build
      working-directory: apps/not-splitwise
      run: pnpm build
    - name: Install Firebase CLI
      run: npm i -g firebase-tools
    - name: Set hosting site in firebase.json
      working-directory: apps/not-splitwise
      env:
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      run: |
        node -e "const fs=require('fs');const p='firebase.json';const j=JSON.parse(fs.readFileSync(p,'utf8'));j.hosting=j.hosting||{};j.hosting.site=process.env.FIREBASE_PROJECT_ID;delete j.hosting.target;fs.writeFileSync(p,JSON.stringify(j));console.log('hosting.site=',j.hosting.site)"
    - name: Deploy to Firebase Hosting (Action)
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: ${{ secrets.GITHUB_TOKEN }}
        firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
        projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
        channelId: live
        entryPoint: apps/not-splitwise
